using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler
{
    public static class Problem2
    {
        // Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
        // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


        public static void Run()

        {
            // Max value of the terms in the Fibonacci sequence
            int limit = 4000000;
            int sum = 0;
            int prev = 1;
            int curr = 2;

            // use a while loop to generate Fibonacci nubmers until current number reaches the four million cap
            while (curr <= limit)
            {
                // checking if curr is an even number, then we add it to sum
                if (curr % 2 == 0)
                {
                    sum += curr;
                }

                // next is a term in the Fibonacci sequence
                int next = prev + curr;
                prev = curr;
                curr = next;
            }

            Console.WriteLine(sum);
        }
        // chatgpt
    }
}