using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Numerics;
using System.Runtime.Intrinsics.X86;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler
{
    public static class Problem29
    {
        // How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

        public static void Run()
        {
            HashSet<BigInteger> distinctTerms = new HashSet<BigInteger>();

            for (int a = 2; a <= 100; a++)
            {
                for (int b = 2; b <= 100; b++)
                {
                    distinctTerms.Add(BigInteger.Pow(a, b)); //a^b
                }
            }

            Console.WriteLine(distinctTerms.Count);
            Console.ReadLine();
        }
    }
}